---
# Configurations set here should be mostly used to setup the environment for
# the bot, such as initial cog load order and other things.
#
# Discord Configurations
# ---

env: # Environmental Variable Names (from .env or defined ENV variables)
  token_envar_name: 'OSU_BOT_TOKEN' # Discord App Bot secret
  api_envar_name: 'OSU_API_TOKEN' # API Client secret
  client_id_name: 'OSU_CLIENT_ID' # API Client ID number
  irc_envar_name: 'OSU_IRC_TOKEN' # osu!chat IRC token

command_prefix: '!'
  # Prefix that the bot will listen to in Discord chat messages
status: 'online'
  # discord.Status [online, idle, dnd, invisible, offline]

activity: # needs a good message
  type: 'watching'
    # discord.ActivityType
  name: "for commands in chat"

# Startup Configurations
# ---
cogs: # Initial cog load order
  - 'cogs.logger'
  - 'cogs.developer'
  - 'cogs.database'
  - 'cogs.api'
disabled_cogs: # overrides cog load order
  -
...